legram.org/bot6468465353:AAFRda05FTM2kCN9woD-O9SJ2i2Vcy3fzfw/getUpdates "HTTP/1.1 200 OK"
Jul 31 00:14:12 server-mbn5xx python[568338]: 2025-07-31 00:14:12,536 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6468465353:AAFRda05FTM2kCN9woD-O9SJ2i2Vcy3fzfw/sendMessage "HTTP/1.1 400 Bad Request"
Jul 31 00:14:12 server-mbn5xx python[568338]: 2025-07-31 00:14:12,538 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Jul 31 00:14:12 server-mbn5xx python[568338]: Traceback (most recent call last):
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/ext/_application.py", line 1311, in process_update
Jul 31 00:14:12 server-mbn5xx python[568338]:     await coroutine
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/ext/_handlers/conversationhandler.py", line 842, in handle_update
Jul 31 00:14:12 server-mbn5xx python[568338]:     new_state: object = await handler.handle_update(
Jul 31 00:14:12 server-mbn5xx python[568338]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/ext/_handlers/basehandler.py", line 158, in handle_update
Jul 31 00:14:12 server-mbn5xx python[568338]:     return await self.callback(update, context)
Jul 31 00:14:12 server-mbn5xx python[568338]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/src/handlers/handlers.py", line 130, in view_user_history
Jul 31 00:14:12 server-mbn5xx python[568338]:     await update.message.reply_text(history_text, parse_mode='Markdown')
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/_message.py", line 1910, in reply_text
Jul 31 00:14:12 server-mbn5xx python[568338]:     return await self.get_bot().send_message(
Jul 31 00:14:12 server-mbn5xx python[568338]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 3055, in send_message
Jul 31 00:14:12 server-mbn5xx python[568338]:     return await super().send_message(
Jul 31 00:14:12 server-mbn5xx python[568338]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/_bot.py", line 1100, in send_message
Jul 31 00:14:12 server-mbn5xx python[568338]:     return await self._send_message(
Jul 31 00:14:12 server-mbn5xx python[568338]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 630, in _send_message
Jul 31 00:14:12 server-mbn5xx python[568338]:     result = await super()._send_message(
Jul 31 00:14:12 server-mbn5xx python[568338]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/_bot.py", line 810, in _send_message
Jul 31 00:14:12 server-mbn5xx python[568338]:     result = await self._post(
Jul 31 00:14:12 server-mbn5xx python[568338]:              ^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/_bot.py", line 698, in _post
Jul 31 00:14:12 server-mbn5xx python[568338]:     return await self._do_post(
Jul 31 00:14:12 server-mbn5xx python[568338]:            ^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 370, in _do_post
Jul 31 00:14:12 server-mbn5xx python[568338]:     return await super()._do_post(
Jul 31 00:14:12 server-mbn5xx python[568338]:            ^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/_bot.py", line 727, in _do_post
Jul 31 00:14:12 server-mbn5xx python[568338]:     result = await request.post(
Jul 31 00:14:12 server-mbn5xx python[568338]:              ^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 197, in post
Jul 31 00:14:12 server-mbn5xx python[568338]:     result = await self._request_wrapper(
Jul 31 00:14:12 server-mbn5xx python[568338]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 00:14:12 server-mbn5xx python[568338]:   File "/root/AI_TelegramBot_from_Nasim-public_version-/venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
Jul 31 00:14:12 server-mbn5xx python[568338]:     raise exception
Jul 31 00:14:12 server-mbn5xx python[568338]: telegram.error.BadRequest: Message is too long
Jul 31 00:14:22 server-mbn5xx python[568338]: 2025-07-31 00:14:22,465 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6468465353:AAFRda05FTM2kCN9woD-O9SJ2i2Vcy3fzfw/getUpdates "HTTP/1.1 200 OK"